version: '3.8'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: lost_and_found
      POSTGRES_USER: yerassyl
      POSTGRES_PASSWORD: 12345era
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=en_US.utf8"
      LC_ALL: en_US.utf8
      LANG: en_US.utf8
      LANGUAGE: en_US.utf8
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U yerassyl -d lost_and_found"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: .
    command: bash -c "python manage.py migrate && python manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - media_volume:/code/media
      - static_volume:/app/staticfiles

      - .:/app
    environment:
      DB_NAME: lost_and_found
      DB_USER: yerassyl
      DB_PASSWORD: 12345era
      DB_HOST: db
      # MinIO settings
      AWS_ACCESS_KEY_ID: minioadmin
      AWS_SECRET_ACCESS_KEY: minioadmin
      AWS_STORAGE_BUCKET_NAME: lost-and-found-media
      AWS_S3_ENDPOINT_URL: http://minio:9000
      AWS_S3_USE_SSL: "false"
      DEFAULT_FILE_STORAGE: storages.backends.s3boto3.S3Boto3Storage
    depends_on:
      db:
        condition: service_healthy
      minio:
        condition: service_healthy

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_DEFAULT_BUCKETS: "lost-and-found-media"
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"  # API port
      - "9001:9001"  # Console port
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  createbuckets:
    image: minio/mc
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc config host add minio http://minio:9000 minioadmin minioadmin) do echo 'Waiting for MinIO...' && sleep 1; done;
      /usr/bin/mc mb minio/lost-and-found-media;
      /usr/bin/mc policy set public minio/lost-and-found-media;
      exit 0;
      "

  nginx:
    image: nginx:1.21-alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/static
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume:
  minio_data: