# Generated by Django 4.2.13 on 2025-04-24 16:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import items.storages


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('items', '0002_alter_founditem_date_found_alter_lostitem_date_lost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='founditem',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='lostitem',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='founditem',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='founditem',
            name='is_claimed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='founditem',
            name='status',
            field=models.CharField(choices=[('found', 'Found'), ('claimed', 'Claimed')], default='found', max_length=10),
        ),
        migrations.AddField(
            model_name='lostitem',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='lostitem',
            name='is_recovered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lostitem',
            name='status',
            field=models.CharField(choices=[('lost', 'Lost'), ('found', 'Found'), ('recovered', 'Recovered')], default='lost', max_length=10),
        ),
        migrations.AlterField(
            model_name='founditem',
            name='date_found',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='founditem',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=items.storages.MediaStorage(), upload_to='found_items/'),
        ),
        migrations.AlterField(
            model_name='founditem',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='founditem',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lostitem',
            name='date_lost',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='lostitem',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=items.storages.MediaStorage(), upload_to='lost_items/'),
        ),
        migrations.AlterField(
            model_name='lostitem',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='lostitem',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
